# Generated by Django 4.0.5 on 2024-02-04 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('constellation_name', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='items/')),
                ('score', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
