# Generated by Django 5.0.1 on 2024-02-04 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_id_image_user_alter_image_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfileConstellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ImageField(upload_to='media/')),
                ('image_name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_prof', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
