# Generated by Django 4.0.5 on 2024-02-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_image_user_profileconstellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileconstellation',
            name='found_dict',
            field=models.CharField(default='none', max_length=10000),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='profileconstellation',
            name='image_id',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
